services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aw_network
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - aw_network

networks:
  aw_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: